- name: Get FMC Policy Assignments
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    fmc_host: 150.1.7.242
    token: 8506dd95-b51c-4f9f-9991-6b6973e9464a
    domain_id: e276abec-e0f2-11e3-8169-6d9ed49b625f
  tasks:
    - name: Deployment
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/{{ domain_id }}/deployment/deploymentrequests"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "{{ token }}"
          Content-Type: "application/json"
        body_format: json
       
      register: deployment

    - name: Display Deployment Response
      debug:
        var: deployment.json
