- name: Generate FMC API access token
  hosts: FMC
  tasks:
    - name: Authenticate with FMC API
      command: "curl -k -H 'Content-Type: application/json' -X POST https://{{ fmc_address }}/api/fmc_platform/v1/auth/generatetoken -d '{\"username\":\"{{ fmc_username }}\",\"password\":\"{{ fmc_password }}\"}'"
      register: curl_result
      ignore_errors: true

    - name: Set access token fact
      set_fact:
        access_token: "{{ curl_result.stdout | from_json | json_query('Token') }}"
