- name: Get Group Devices Cisco FMC
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    token: "eff12252-4ddd-4018-ab88-4604f041e734"
    domain_id: "e276abec-e0f2-11e3-8169-6d9ed49b625f"
  tasks:
    - name: Get Device Group
      ansible.builtin.uri:
        url: "https://150.1.7.242/api/fmc_config/v1/domain/{{ domain_id }}/devicegroups/devicegrouprecords"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "{{ token }}"
      register: device_info

    - name: Display Results
      ansible.builtin.debug:
        var: device_info.json
