---
- name: Get Policies from Cisco FMC
  hosts: webservers
  connection : httpapi
  become: false
  gather_facts: no
  vars:
    fmc_host: <150.1.7.242>
    credentials: "apiuser:Cisco123"
  tasks:
    - name: Get Network Analysis Policies
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/networkanalysispolicies"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "85c3b63a-ee57-405b-83d2-54e7504eb04f"
        
      register: net_policies

    - name: Display Results
      debug:
        var: item.json
      with_items:
        - "{{ net_policies }}"
