---
- name: Generate FMC API access token
  hosts: webservers
  connection : httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
  tasks:
    - name: Get Access Control Policies
      ansible.builtin.uri:
        url: "https://150.1.7.242/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "85c3b63a-ee57-405b-83d2-54e7504eb04f"
      register: access_policies

    - name: Display token
      debug:
        var: access_policies.json
