- name: Get FMC Policy Assignments
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    fmc_host: 150.1.7.242
    token: a117f19b-e07d-4782-8fd5-4313f2d2e8ed
    domain_id: e276abec-e0f2-11e3-8169-6d9ed49b625f
  tasks:
    - name: Deployment
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/deployment/deployabledevices"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "{{ token }}"
       
      register: deployment

    - name: Display Deployment Response
      debug:
        var: deployment.json
