- name: Get Access Control Rules from Cisco FMC
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    access_policy_name: "FTD_Policy"  # Update with the desired access policy name
  
  tasks:
    - name: Get Access Control Policy ID
      uri:
        url: "https://150.01.7.242/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "17f5fb30-15c3-46c1-a4ac-6863a7bb25bc"
      register: access_policies

    - name: Find Access Policy ID
      set_fact:
        access_policy_id: "{{ item.id }}"
      loop: "{{ access_policies.json.items }}"
      when: item.name == access_policy_name

    - name: Get Access Control Rules
      uri:
        url: "https://150.1.7.242/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies/{{ access_policy_id }}/accessrules"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "17f5fb30-15c3-46c1-a4ac-6863a7bb25bc"
      register: access_rules

    - name: Display Results
      debug:
        var: access_rules.json
