---
- name: Get Access Control Rules from Cisco FMC
  hosts: FMC
  connection: httpapi
  gather_facts: no
  vars:
    fmc_host: <150.1.7.242>
    fmc_username: <admin>
    fmc_password: <Admin123>
  tasks:
    - name: Get Access Control Policy ID
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/default/policy/accesspolicies"
        method: GET
        user: "{{ fmc_username }}"
        password: "{{ fmc_password }}"
        headers:
          Accept: "application/json"
        validate_certs: no
      register: access_policies

    - name: Get Access Control Rules
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/default/policy/accesspolicies/{{ access_policies.json['items'][0]['id'] }}/accessrules"
        method: GET
        user: "{{ fmc_username }}"
        password: "{{ fmc_password }}"
        headers:
          Accept: "application/json"
        validate_certs: no
      register: access_rules

    - name: Display Results
      debug:
        var: access_rules.json