---
- name: Gte FMC access policies
  hosts: webservers
  connection : httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "adminapi:Ad+in123"
  tasks:
    - name: Get Access Control Policies
      ansible.builtin.uri:
        url: "https://150.1.7.242/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "9e012008-f545-4f67-b644-71e8e8a494c9"
      register: access_policies

    - name: Display token
      debug:
        var: access_policies.json
