- name: Get Audit Information Cisco FMC
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    token: "cd17c326-d9bf-40a3-baa8-36e8cd615a05"
    domain_id: "e276abec-e0f2-11e3-8169-6d9ed49b625f"
  tasks:
    - name: Get Audit Object
      ansible.builtin.uri:
        url: "https://150.1.7.242/api/fmc_platform/v1/domain/{{ domain_id }}/audit/auditrecords"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "{{ token }}"
      register: Audit_info

    - name: Display Results
      ansible.builtin.debug:
        var: Audit_info.json
