- name: Get FMC Policy Assignments
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
    fmc_host: 150.1.7.242
    token: 06e78baf-a0be-479d-99ae-121c4f26d551
    domain_id: e276abec-e0f2-11e3-8169-6d9ed49b625f
  tasks:
    - name: Get Policy Assignments
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/{{ domain_id }}/assignment/policyassignments"
        method: GET
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
          X-auth-access-token: "{{ token }}"
      register: policy_assignments

    - name: Display Policy Assignments
      debug:
        var: policy_assignments.json
