---
- name: Get Access Control Rules from Cisco FMC
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: apiuser:Cisco123
    access_policy_name: "{{ hostvars[inventory_hostname]['access_policy_name'] }}"
    fmc_host: 150.1.7.242
    token: a117f19b-e07d-4782-8fd5-4313f2d2e8ed
  tasks:
    - name: Get Access Control Policy ID
      uri:
        url: https://{{ fmc_host
          }}/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies
        method: GET
        validate_certs: no
        headers:
          Authorization: Basic {{ credentials | b64encode }}
          X-auth-access-token: "{{ token }}"
      register: access_policies
    - name: Find Access Policy ID
      set_fact:
        access_policy_id: "{{ item.id }}"
      loop: "{{ access_policies.json['items'] }}"
      when: item.name == access_policy_name
    - name: Get Access Control Rules
      uri:
        url: https://{{ fmc_host
          }}/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies/{{
          access_policy_id }}/accessrules
        method: GET
        validate_certs: no
        headers:
          Authorization: Basic {{ credentials | b64encode }}
          X-auth-access-token: "{{ token }}"
      register: access_rules
    - name: Display Results
      debug:
        var: access_rules.json
