---
- name: Assign Access Control Policy to Device Group on Cisco FMC
  hosts: FMC
  connection: httpapi
  gather_facts: no
  vars:
    fmc_host: <150.1.7.242>
    fmc_username: <admin>
    fmc_password: <Admin123>
    device_group_name: "{{ device_group_name }}"
    access_policy_name: "{{ access_policy_name }}"
    domain_uuid: <e276abec-e0f2-11e3-8169-6d9ed49b625f> 
  tasks:
    - name: Get Device Group ID
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/{{ domain_uuid }}/devicegroups?filter=name:{{ device_group_name }}"
        method: GET
        user: "{{ fmc_username }}"
        password: "{{ fmc_password }}"
        headers:
          Accept: "application/json"
        validate_certs: no
      register: device_group

    - name: Get Access Control Policy ID
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/{{ domain_uuid }}/policy/accesspolicies?filter=name:{{ access_policy_name }}"
        method: GET
        user: "{{ fmc_username }}"
        password: "{{ fmc_password }}"
        headers:
          Accept: "application/json"
        validate_certs: no
      register: access_policy

    - name: Assign Access Control Policy to Device Group
      uri:
        url: "https://{{ fmc_host }}/api/fmc_config/v1/domain/default/devicegroups/{{ device_group.json['items'][0]['id'] }}/accesspolicies"
        method: POST
        user: "{{ fmc_username }}"
        password: "{{ fmc_password }}"
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        validate_certs: no
        body:
          id: "{{ access_policy.json['items'][0]['id'] }}"
      register: assign_policy

    - name: Display Results
      debug:
        var: assign_policy.json