---
- name: Generate FMC API access token
  hosts: webservers
  connection : httpapi
  become : false
  gather_facts: no
  vars:
    credentials: "adminapi:Ad+in123"
  tasks:
    - name: Get authentication token
      uri:
        url: "https://150.1.7.242/api/fmc_platform/v1/auth/generatetoken"
        method: POST
        validate_certs: no
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
        return_content: yes
       
      register: token_response
      failed_when: token_response.status not in [200, 204] #now its work 
      
    - name: Display token
      debug:
        var: 
        - token_response.json.access_token
        - token_response.json.x_auth_access_token
