---
- name: Generate FMC API access token
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
  tasks:
    - name: Send HTTP request
      uri:
        url: "https://150.1.7.242/api/fmc_platform/v1/auth/generatetoken"
        return_content: no
        method: GET
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
        validate_certs: no
      register: response
      
    - name: Print headers
      debug:
        var: response.headers
      
         
