---
- name: Generate FMC API access token
  hosts: webservers
  connection : httpapi
  become: false
  gather_facts: no
  vars:
    credentials: "apiuser:Cisco123"
  tasks:
    - name: Get authentication token
      ansible.builtin.uri:
        url: "https://150.1.7.242/api/fmc_platform/v1/auth/generatetoken"
        method: POST
        headers:
          Authorization: "Basic {{ credentials | b64encode }}"
        return_content: yes
        validate_certs: no
      register: token_response
      
    - name: Set access token
      set_fact:
        access_token: "{{ token_response.headers.get['x_auth_access_token'] }}"

    - name: Display token
      debug:
        var:  access_token.json
